#!/usr/bin/env python3.7
# -*- coding: utf-8 -*-

# Authors:  Maria Masarova <xmasar13>
#           Jan Pristas <xprist06>

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRect
import sys
import os
import threading
from qswitchbutton import QSwitchButton

import init_script
from tractor import ProductionLine

# window title
WIN_TITLE = "HMIv2.0"


def closeEvent():
    os._exit(0)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 781)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 751, 781))
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.front_remover = QtWidgets.QWidget(self.widget)
        self.front_remover.setGeometry(QtCore.QRect(330, 30, 101, 90))
        self.front_remover.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.front_remover.setObjectName("front_remover")
        self.front_remover_label = QtWidgets.QLabel(self.front_remover)
        self.front_remover_label.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.front_remover_label.setFont(font)
        self.front_remover_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.front_remover_label.setAlignment(QtCore.Qt.AlignCenter)
        self.front_remover_label.setObjectName("front_remover_label")
        self.front_remover_indicator = QtWidgets.QLabel(self.front_remover)
        self.front_remover_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.front_remover_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.front_remover_indicator.setText("")
        self.front_remover_indicator.setObjectName("front_remover_indicator")
        self.left_remover = QtWidgets.QWidget(self.widget)
        self.left_remover.setGeometry(QtCore.QRect(30, 280, 101, 90))
        self.left_remover.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.left_remover.setObjectName("left_remover")
        self.left_remover_label = QtWidgets.QLabel(self.left_remover)
        self.left_remover_label.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.left_remover_label.setFont(font)
        self.left_remover_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.left_remover_label.setAlignment(QtCore.Qt.AlignCenter)
        self.left_remover_label.setObjectName("left_remover_label")
        self.left_remover_indicator = QtWidgets.QLabel(self.left_remover)
        self.left_remover_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.left_remover_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.left_remover_indicator.setText("")
        self.left_remover_indicator.setObjectName("left_remover_indicator")
        self.right_remover = QtWidgets.QWidget(self.widget)
        self.right_remover.setGeometry(QtCore.QRect(630, 280, 101, 90))
        self.right_remover.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.right_remover.setObjectName("right_remover")
        self.right_remover_label = QtWidgets.QLabel(self.right_remover)
        self.right_remover_label.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.right_remover_label.setFont(font)
        self.right_remover_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.right_remover_label.setAlignment(QtCore.Qt.AlignCenter)
        self.right_remover_label.setObjectName("right_remover_label")
        self.right_remover_indicator = QtWidgets.QLabel(self.right_remover)
        self.right_remover_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.right_remover_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.right_remover_indicator.setText("")
        self.right_remover_indicator.setObjectName("right_remover_indicator")
        self.front_conveyor = QtWidgets.QWidget(self.widget)
        self.front_conveyor.setGeometry(QtCore.QRect(330, 130, 101, 130))
        self.front_conveyor.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.front_conveyor.setObjectName("front_conveyor")
        self.front_conveyor_label = QtWidgets.QLabel(self.front_conveyor)
        self.front_conveyor_label.setGeometry(QtCore.QRect(10, 40, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.front_conveyor_label.setFont(font)
        self.front_conveyor_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.front_conveyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.front_conveyor_label.setObjectName("front_conveyor_label")
        self.front_conveyor_indicator = QtWidgets.QLabel(self.front_conveyor)
        self.front_conveyor_indicator.setGeometry(QtCore.QRect(10, 20, 14, 14))
        self.front_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.front_conveyor_indicator.setText("")
        self.front_conveyor_indicator.setObjectName("front_conveyor_indicator")
        self.sorter = QtWidgets.QWidget(self.widget)
        self.sorter.setGeometry(QtCore.QRect(330, 280, 101, 90))
        self.sorter.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.sorter.setObjectName("sorter")
        self.sorter_label = QtWidgets.QLabel(self.sorter)
        self.sorter_label.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sorter_label.setFont(font)
        self.sorter_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.sorter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sorter_label.setObjectName("sorter_label")
        self.left_arrow = QtWidgets.QToolButton(self.sorter)
        self.left_arrow.setGeometry(QtCore.QRect(0, 35, 21, 21))
        self.left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.left_arrow.setText("")
        self.left_arrow.setArrowType(QtCore.Qt.LeftArrow)
        self.left_arrow.setObjectName("left_arrow")
        self.front_arrow = QtWidgets.QToolButton(self.sorter)
        self.front_arrow.setGeometry(QtCore.QRect(42, 0, 21, 21))
        self.front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.front_arrow.setText("")
        self.front_arrow.setArrowType(QtCore.Qt.UpArrow)
        self.front_arrow.setObjectName("front_arrow")
        self.right_arrow = QtWidgets.QToolButton(self.sorter)
        self.right_arrow.setGeometry(QtCore.QRect(82, 35, 21, 21))
        self.right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.right_arrow.setText("")
        self.right_arrow.setArrowType(QtCore.Qt.RightArrow)
        self.right_arrow.setObjectName("right_arrow")
        self.left_conveyor = QtWidgets.QWidget(self.widget)
        self.left_conveyor.setGeometry(QtCore.QRect(140, 280, 171, 91))
        self.left_conveyor.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.left_conveyor.setObjectName("left_conveyor")
        self.left_conveyor_label = QtWidgets.QLabel(self.left_conveyor)
        self.left_conveyor_label.setGeometry(QtCore.QRect(10, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.left_conveyor_label.setFont(font)
        self.left_conveyor_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.left_conveyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.left_conveyor_label.setObjectName("left_conveyor_label")
        self.left_conveyor_indicator = QtWidgets.QLabel(self.left_conveyor)
        self.left_conveyor_indicator.setGeometry(QtCore.QRect(20, 10, 14, 14))
        self.left_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.left_conveyor_indicator.setText("")
        self.left_conveyor_indicator.setObjectName("left_conveyor_indicator")
        self.right_conveyor = QtWidgets.QWidget(self.widget)
        self.right_conveyor.setGeometry(QtCore.QRect(450, 280, 171, 91))
        self.right_conveyor.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.right_conveyor.setObjectName("right_conveyor")
        self.right_conveyor_label = QtWidgets.QLabel(self.right_conveyor)
        self.right_conveyor_label.setGeometry(QtCore.QRect(10, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.right_conveyor_label.setFont(font)
        self.right_conveyor_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.right_conveyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.right_conveyor_label.setObjectName("right_conveyor_label")
        self.right_conveyor_indicator = QtWidgets.QLabel(self.right_conveyor)
        self.right_conveyor_indicator.setGeometry(QtCore.QRect(20, 10, 14, 14))
        self.right_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.right_conveyor_indicator.setText("")
        self.right_conveyor_indicator.setObjectName("right_conveyor_indicator")
        self.load_scale = QtWidgets.QWidget(self.widget)
        self.load_scale.setGeometry(QtCore.QRect(330, 390, 101, 130))
        self.load_scale.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.load_scale.setObjectName("load_scale")
        self.load_scale_label = QtWidgets.QLabel(self.load_scale)
        self.load_scale_label.setGeometry(QtCore.QRect(10, 50, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.load_scale_label.setFont(font)
        self.load_scale_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.load_scale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.load_scale_label.setObjectName("load_scale_label")
        self.load_scale_switch = QSwitchButton(self.load_scale)
        self.load_scale_switch.setGeometry(QtCore.QRect(60, 20, 31, 16))
        self.load_scale_switch.setText("")
        self.load_scale_switch.setObjectName("load_scale_switch")
        self.load_scale_indicator = QtWidgets.QLabel(self.load_scale)
        self.load_scale_indicator.setGeometry(QtCore.QRect(10, 20, 14, 14))
        self.load_scale_indicator.setStyleSheet("border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.load_scale_indicator.setText("")
        self.load_scale_indicator.setObjectName("load_scale_indicator")
        self.entry_conveyor = QtWidgets.QWidget(self.widget)
        self.entry_conveyor.setGeometry(QtCore.QRect(330, 530, 101, 130))
        self.entry_conveyor.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.entry_conveyor.setObjectName("entry_conveyor")
        self.entry_conveyor_label = QtWidgets.QLabel(self.entry_conveyor)
        self.entry_conveyor_label.setGeometry(QtCore.QRect(10, 40, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.entry_conveyor_label.setFont(font)
        self.entry_conveyor_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.entry_conveyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.entry_conveyor_label.setObjectName("entry_conveyor_label")
        self.entry_conveyor_switch = QSwitchButton(self.entry_conveyor)
        self.entry_conveyor_switch.setGeometry(QtCore.QRect(60, 10, 31, 16))
        self.entry_conveyor_switch.setText("")
        self.entry_conveyor_switch.setObjectName("entry_conveyor_switch")
        self.entry_conveyor_indicator = QtWidgets.QLabel(self.entry_conveyor)
        self.entry_conveyor_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.entry_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.entry_conveyor_indicator.setText("")
        self.entry_conveyor_indicator.setObjectName("entry_conveyor_indicator")
        self.send = QtWidgets.QWidget(self.widget)
        self.send.setGeometry(QtCore.QRect(330, 670, 101, 90))
        self.send.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.send.setObjectName("send")
        self.send_label = QtWidgets.QLabel(self.send)
        self.send_label.setGeometry(QtCore.QRect(10, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_label.setFont(font)
        self.send_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.send_label.setAlignment(QtCore.Qt.AlignCenter)
        self.send_label.setObjectName("send_label")
        self.send_left_arrow = QtWidgets.QToolButton(self.send)
        self.send_left_arrow.setGeometry(QtCore.QRect(82, 35, 21, 21))
        self.send_left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.send_left_arrow.setText("")
        self.send_left_arrow.setArrowType(QtCore.Qt.LeftArrow)
        self.send_left_arrow.setObjectName("send_left_arrow")
        self.send_front_arrow = QtWidgets.QToolButton(self.send)
        self.send_front_arrow.setGeometry(QtCore.QRect(42, 0, 21, 21))
        self.send_front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.send_front_arrow.setText("")
        self.send_front_arrow.setArrowType(QtCore.Qt.UpArrow)
        self.send_front_arrow.setObjectName("send_front_arrow")
        self.send_right_arrow = QtWidgets.QToolButton(self.send)
        self.send_right_arrow.setGeometry(QtCore.QRect(0, 35, 21, 21))
        self.send_right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.send_right_arrow.setText("")
        self.send_right_arrow.setArrowType(QtCore.Qt.RightArrow)
        self.send_right_arrow.setObjectName("send_right_arrow")
        self.front_right_conveyor = QtWidgets.QWidget(self.widget)
        self.front_right_conveyor.setGeometry(QtCore.QRect(440, 670, 171, 91))
        self.front_right_conveyor.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.front_right_conveyor.setObjectName("front_right_conveyor")
        self.front_right_conveyor_label = QtWidgets.QLabel(self.front_right_conveyor)
        self.front_right_conveyor_label.setGeometry(QtCore.QRect(10, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.front_right_conveyor_label.setFont(font)
        self.front_right_conveyor_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.front_right_conveyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.front_right_conveyor_label.setObjectName("front_right_conveyor_label")
        self.front_right_conveyor_indicator = QtWidgets.QLabel(self.front_right_conveyor)
        self.front_right_conveyor_indicator.setGeometry(QtCore.QRect(20, 10, 14, 14))
        self.front_right_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.front_right_conveyor_indicator.setText("")
        self.front_right_conveyor_indicator.setObjectName("front_right_conveyor_indicator")
        self.front_left_conveyor = QtWidgets.QWidget(self.widget)
        self.front_left_conveyor.setGeometry(QtCore.QRect(150, 670, 171, 91))
        self.front_left_conveyor.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.front_left_conveyor.setObjectName("front_left_conveyor")
        self.front_left_conveyor_label = QtWidgets.QLabel(self.front_left_conveyor)
        self.front_left_conveyor_label.setGeometry(QtCore.QRect(10, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.front_left_conveyor_label.setFont(font)
        self.front_left_conveyor_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.front_left_conveyor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.front_left_conveyor_label.setObjectName("front_left_conveyor_label")
        self.front_left_conveyor_indicator = QtWidgets.QLabel(self.front_left_conveyor)
        self.front_left_conveyor_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.front_left_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.front_left_conveyor_indicator.setText("")
        self.front_left_conveyor_indicator.setObjectName("front_left_conveyor_indicator")
        self.right_emitter = QtWidgets.QWidget(self.widget)
        self.right_emitter.setGeometry(QtCore.QRect(620, 670, 101, 90))
        self.right_emitter.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.right_emitter.setObjectName("right_emitter")
        self.right_emitter_label = QtWidgets.QLabel(self.right_emitter)
        self.right_emitter_label.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.right_emitter_label.setFont(font)
        self.right_emitter_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.right_emitter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.right_emitter_label.setObjectName("right_emitter_label")
        self.right_emitter_indicator = QtWidgets.QLabel(self.right_emitter)
        self.right_emitter_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.right_emitter_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.right_emitter_indicator.setText("")
        self.right_emitter_indicator.setObjectName("right_emitter_indicator")
        self.right_emitter_switch = QSwitchButton(self.right_emitter)
        self.right_emitter_switch.setGeometry(QtCore.QRect(60, 10, 31, 16))
        self.right_emitter_switch.setText("")
        self.right_emitter_switch.setObjectName("right_emitter_switch")
        self.left_emitter = QtWidgets.QWidget(self.widget)
        self.left_emitter.setGeometry(QtCore.QRect(40, 670, 101, 90))
        self.left_emitter.setStyleSheet("border:2px solid rgb(0, 0, 0);")
        self.left_emitter.setObjectName("left_emitter")
        self.left_emitter_label = QtWidgets.QLabel(self.left_emitter)
        self.left_emitter_label.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.left_emitter_label.setFont(font)
        self.left_emitter_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.left_emitter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.left_emitter_label.setObjectName("left_emitter_label")
        self.left_emitter_indicator = QtWidgets.QLabel(self.left_emitter)
        self.left_emitter_indicator.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.left_emitter_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        self.left_emitter_indicator.setText("")
        self.left_emitter_indicator.setObjectName("left_emitter_indicator")
        self.left_emitter_switch = QSwitchButton(self.left_emitter)
        self.left_emitter_switch.setGeometry(QtCore.QRect(60, 10, 31, 16))
        self.left_emitter_switch.setText("")
        self.left_emitter_switch.setObjectName("left_emitter_switch")
        self.at_scale_entry_label = QtWidgets.QLabel(self.widget)
        self.at_scale_entry_label.setGeometry(QtCore.QRect(440, 500, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_scale_entry_label.setFont(font)
        self.at_scale_entry_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_scale_entry_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_scale_entry_label.setObjectName("at_scale_entry_label")
        self.at_scale_label = QtWidgets.QLabel(self.widget)
        self.at_scale_label.setGeometry(QtCore.QRect(440, 430, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_scale_label.setFont(font)
        self.at_scale_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_scale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_scale_label.setObjectName("at_scale_label")
        self.at_scale_exit_label = QtWidgets.QLabel(self.widget)
        self.at_scale_exit_label.setGeometry(QtCore.QRect(440, 390, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_scale_exit_label.setFont(font)
        self.at_scale_exit_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_scale_exit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_scale_exit_label.setObjectName("at_scale_exit_label")
        self.front_counter_label = QtWidgets.QLabel(self.widget)
        self.front_counter_label.setGeometry(QtCore.QRect(330, 10, 101, 21))
        self.front_counter_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.front_counter_label.setObjectName("front_counter_label")
        self.at_scale_entry_sensor = QtWidgets.QWidget(self.widget)
        self.at_scale_entry_sensor.setGeometry(QtCore.QRect(320, 510, 120, 2))
        self.at_scale_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_scale_entry_sensor.setObjectName("at_scale_entry_sensor")
        self.at_scale_sensor = QtWidgets.QWidget(self.widget)
        self.at_scale_sensor.setGeometry(QtCore.QRect(320, 440, 120, 2))
        self.at_scale_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_scale_sensor.setObjectName("at_scale_sensor")
        self.at_scale_exit_sensor = QtWidgets.QWidget(self.widget)
        self.at_scale_exit_sensor.setGeometry(QtCore.QRect(320, 400, 120, 2))
        self.at_scale_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_scale_exit_sensor.setObjectName("at_scale_exit_sensor")
        self.at_scale_entry_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_scale_entry_arrow_2.setGeometry(QtCore.QRect(430, 501, 21, 21))
        self.at_scale_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_entry_arrow_2.setText("")
        self.at_scale_entry_arrow_2.setArrowType(QtCore.Qt.LeftArrow)
        self.at_scale_entry_arrow_2.setObjectName("at_scale_entry_arrow_2")
        self.at_scale_entry_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_scale_entry_arrow_1.setGeometry(QtCore.QRect(310, 501, 21, 21))
        self.at_scale_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_entry_arrow_1.setText("")
        self.at_scale_entry_arrow_1.setArrowType(QtCore.Qt.RightArrow)
        self.at_scale_entry_arrow_1.setObjectName("at_scale_entry_arrow_1")
        self.at_scale_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_scale_arrow_2.setGeometry(QtCore.QRect(430, 431, 21, 21))
        self.at_scale_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_arrow_2.setText("")
        self.at_scale_arrow_2.setArrowType(QtCore.Qt.LeftArrow)
        self.at_scale_arrow_2.setObjectName("at_scale_arrow_2")
        self.at_scale_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_scale_arrow_1.setGeometry(QtCore.QRect(310, 431, 21, 21))
        self.at_scale_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_arrow_1.setText("")
        self.at_scale_arrow_1.setArrowType(QtCore.Qt.RightArrow)
        self.at_scale_arrow_1.setObjectName("at_scale_arrow_1")
        self.at_scale_exit_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_scale_exit_arrow_1.setGeometry(QtCore.QRect(310, 391, 21, 21))
        self.at_scale_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_exit_arrow_1.setText("")
        self.at_scale_exit_arrow_1.setArrowType(QtCore.Qt.RightArrow)
        self.at_scale_exit_arrow_1.setObjectName("at_scale_exit_arrow_1")
        self.at_scale_exit_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_scale_exit_arrow_2.setGeometry(QtCore.QRect(430, 391, 21, 21))
        self.at_scale_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_exit_arrow_2.setText("")
        self.at_scale_exit_arrow_2.setArrowType(QtCore.Qt.LeftArrow)
        self.at_scale_exit_arrow_2.setObjectName("at_scale_exit_arrow_2")
        self.weight_label = QtWidgets.QLabel(self.widget)
        self.weight_label.setGeometry(QtCore.QRect(480, 430, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weight_label.setFont(font)
        self.weight_label.setObjectName("weight_label")
        self.left_counter_label = QtWidgets.QLabel(self.widget)
        self.left_counter_label.setGeometry(QtCore.QRect(30, 260, 101, 21))
        self.left_counter_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.left_counter_label.setObjectName("left_counter_label")
        self.right_counter_label = QtWidgets.QLabel(self.widget)
        self.right_counter_label.setGeometry(QtCore.QRect(630, 260, 101, 21))
        self.right_counter_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.right_counter_label.setObjectName("right_counter_label")
        self.at_forward_entry_sensor = QtWidgets.QWidget(self.widget)
        self.at_forward_entry_sensor.setGeometry(QtCore.QRect(320, 250, 120, 2))
        self.at_forward_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_forward_entry_sensor.setObjectName("at_forward_entry_sensor")
        self.at_forward_entry_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_forward_entry_arrow_1.setGeometry(QtCore.QRect(310, 241, 21, 21))
        self.at_forward_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_forward_entry_arrow_1.setText("")
        self.at_forward_entry_arrow_1.setArrowType(QtCore.Qt.RightArrow)
        self.at_forward_entry_arrow_1.setObjectName("at_forward_entry_arrow_1")
        self.at_forward_entry_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_forward_entry_arrow_2.setGeometry(QtCore.QRect(430, 241, 21, 21))
        self.at_forward_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_forward_entry_arrow_2.setText("")
        self.at_forward_entry_arrow_2.setArrowType(QtCore.Qt.LeftArrow)
        self.at_forward_entry_arrow_2.setObjectName("at_forward_entry_arrow_2")
        self.at_forward_entry_label = QtWidgets.QLabel(self.widget)
        self.at_forward_entry_label.setGeometry(QtCore.QRect(440, 240, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_forward_entry_label.setFont(font)
        self.at_forward_entry_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_forward_entry_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_forward_entry_label.setObjectName("at_forward_entry_label")
        self.at_left_entry_sensor = QtWidgets.QWidget(self.widget)
        self.at_left_entry_sensor.setGeometry(QtCore.QRect(300, 270, 2, 112))
        self.at_left_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_left_entry_sensor.setObjectName("at_left_entry_sensor")
        self.at_left_entry_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_left_entry_arrow_1.setGeometry(QtCore.QRect(291, 260, 21, 21))
        self.at_left_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_left_entry_arrow_1.setText("")
        self.at_left_entry_arrow_1.setArrowType(QtCore.Qt.DownArrow)
        self.at_left_entry_arrow_1.setObjectName("at_left_entry_arrow_1")
        self.at_left_entry_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_left_entry_arrow_2.setGeometry(QtCore.QRect(291, 370, 21, 21))
        self.at_left_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_left_entry_arrow_2.setText("")
        self.at_left_entry_arrow_2.setArrowType(QtCore.Qt.UpArrow)
        self.at_left_entry_arrow_2.setObjectName("at_left_entry_arrow_2")
        self.at_right_entry_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_right_entry_arrow_2.setGeometry(QtCore.QRect(451, 370, 21, 21))
        self.at_right_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_right_entry_arrow_2.setText("")
        self.at_right_entry_arrow_2.setArrowType(QtCore.Qt.UpArrow)
        self.at_right_entry_arrow_2.setObjectName("at_right_entry_arrow_2")
        self.at_right_entry_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_right_entry_arrow_1.setGeometry(QtCore.QRect(451, 260, 21, 21))
        self.at_right_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_right_entry_arrow_1.setText("")
        self.at_right_entry_arrow_1.setArrowType(QtCore.Qt.DownArrow)
        self.at_right_entry_arrow_1.setObjectName("at_right_entry_arrow_1")
        self.at_right_entry_sensor = QtWidgets.QWidget(self.widget)
        self.at_right_entry_sensor.setGeometry(QtCore.QRect(460, 270, 2, 112))
        self.at_right_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_right_entry_sensor.setObjectName("at_right_entry_sensor")
        self.at_right_entry_label = QtWidgets.QLabel(self.widget)
        self.at_right_entry_label.setGeometry(QtCore.QRect(460, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_right_entry_label.setFont(font)
        self.at_right_entry_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_right_entry_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_right_entry_label.setObjectName("at_right_entry_label")
        self.at_left_entry_label = QtWidgets.QLabel(self.widget)
        self.at_left_entry_label.setGeometry(QtCore.QRect(270, 260, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_left_entry_label.setFont(font)
        self.at_left_entry_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_left_entry_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_left_entry_label.setObjectName("at_left_entry_label")
        self.at_right_exit_label = QtWidgets.QLabel(self.widget)
        self.at_right_exit_label.setGeometry(QtCore.QRect(590, 240, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_right_exit_label.setFont(font)
        self.at_right_exit_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_right_exit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_right_exit_label.setObjectName("at_right_exit_label")
        self.at_right_exit_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_right_exit_arrow_1.setGeometry(QtCore.QRect(601, 260, 21, 21))
        self.at_right_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_right_exit_arrow_1.setText("")
        self.at_right_exit_arrow_1.setArrowType(QtCore.Qt.DownArrow)
        self.at_right_exit_arrow_1.setObjectName("at_right_exit_arrow_1")
        self.at_right_exit_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_right_exit_arrow_2.setGeometry(QtCore.QRect(601, 370, 21, 21))
        self.at_right_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_right_exit_arrow_2.setText("")
        self.at_right_exit_arrow_2.setArrowType(QtCore.Qt.UpArrow)
        self.at_right_exit_arrow_2.setObjectName("at_right_exit_arrow_2")
        self.at_right_exit_sensor = QtWidgets.QWidget(self.widget)
        self.at_right_exit_sensor.setGeometry(QtCore.QRect(610, 270, 2, 112))
        self.at_right_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_right_exit_sensor.setObjectName("at_right_exit_sensor")
        self.at_left_exit_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_left_exit_arrow_2.setGeometry(QtCore.QRect(140, 370, 21, 21))
        self.at_left_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_left_exit_arrow_2.setText("")
        self.at_left_exit_arrow_2.setArrowType(QtCore.Qt.UpArrow)
        self.at_left_exit_arrow_2.setObjectName("at_left_exit_arrow_2")
        self.at_left_exit_sensor = QtWidgets.QWidget(self.widget)
        self.at_left_exit_sensor.setGeometry(QtCore.QRect(149, 270, 2, 112))
        self.at_left_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_left_exit_sensor.setObjectName("at_left_exit_sensor")
        self.at_left_exit_label = QtWidgets.QLabel(self.widget)
        self.at_left_exit_label.setGeometry(QtCore.QRect(129, 240, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_left_exit_label.setFont(font)
        self.at_left_exit_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_left_exit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_left_exit_label.setObjectName("at_left_exit_label")
        self.at_left_exit_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_left_exit_arrow_1.setGeometry(QtCore.QRect(140, 260, 21, 21))
        self.at_left_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_left_exit_arrow_1.setText("")
        self.at_left_exit_arrow_1.setArrowType(QtCore.Qt.DownArrow)
        self.at_left_exit_arrow_1.setObjectName("at_left_exit_arrow_1")
        self.sent_from_right_label = QtWidgets.QLabel(self.widget)
        self.sent_from_right_label.setGeometry(QtCore.QRect(430, 630, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sent_from_right_label.setFont(font)
        self.sent_from_right_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.sent_from_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sent_from_right_label.setObjectName("sent_from_right_label")
        self.sent_from_right_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.sent_from_right_arrow_1.setGeometry(QtCore.QRect(441, 650, 21, 21))
        self.sent_from_right_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.sent_from_right_arrow_1.setText("")
        self.sent_from_right_arrow_1.setArrowType(QtCore.Qt.DownArrow)
        self.sent_from_right_arrow_1.setObjectName("sent_from_right_arrow_1")
        self.sent_from_right_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.sent_from_right_arrow_2.setGeometry(QtCore.QRect(441, 760, 21, 21))
        self.sent_from_right_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.sent_from_right_arrow_2.setText("")
        self.sent_from_right_arrow_2.setArrowType(QtCore.Qt.UpArrow)
        self.sent_from_right_arrow_2.setObjectName("sent_from_right_arrow_2")
        self.sent_from_right_sensor = QtWidgets.QWidget(self.widget)
        self.sent_from_right_sensor.setGeometry(QtCore.QRect(450, 660, 2, 112))
        self.sent_from_right_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.sent_from_right_sensor.setObjectName("sent_from_right_sensor")
        self.sent_from_left_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.sent_from_left_arrow_2.setGeometry(QtCore.QRect(300, 760, 21, 21))
        self.sent_from_left_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.sent_from_left_arrow_2.setText("")
        self.sent_from_left_arrow_2.setArrowType(QtCore.Qt.UpArrow)
        self.sent_from_left_arrow_2.setObjectName("sent_from_left_arrow_2")
        self.sent_from_left_label = QtWidgets.QLabel(self.widget)
        self.sent_from_left_label.setGeometry(QtCore.QRect(289, 630, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sent_from_left_label.setFont(font)
        self.sent_from_left_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.sent_from_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sent_from_left_label.setObjectName("sent_from_left_label")
        self.sent_from_left_sensor = QtWidgets.QWidget(self.widget)
        self.sent_from_left_sensor.setGeometry(QtCore.QRect(309, 660, 2, 112))
        self.sent_from_left_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.sent_from_left_sensor.setObjectName("sent_from_left_sensor")
        self.sent_from_left_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.sent_from_left_arrow_1.setGeometry(QtCore.QRect(300, 650, 21, 21))
        self.sent_from_left_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.sent_from_left_arrow_1.setText("")
        self.sent_from_left_arrow_1.setArrowType(QtCore.Qt.DownArrow)
        self.sent_from_left_arrow_1.setObjectName("sent_from_left_arrow_1")
        self.at_forward_exit_label = QtWidgets.QLabel(self.widget)
        self.at_forward_exit_label.setGeometry(QtCore.QRect(440, 129, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.at_forward_exit_label.setFont(font)
        self.at_forward_exit_label.setStyleSheet("border:0px solid rgb(0, 0, 0);")
        self.at_forward_exit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.at_forward_exit_label.setObjectName("at_forward_exit_label")
        self.at_forward_exit_arrow_1 = QtWidgets.QToolButton(self.widget)
        self.at_forward_exit_arrow_1.setGeometry(QtCore.QRect(310, 130, 21, 21))
        self.at_forward_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_forward_exit_arrow_1.setText("")
        self.at_forward_exit_arrow_1.setArrowType(QtCore.Qt.RightArrow)
        self.at_forward_exit_arrow_1.setObjectName("at_forward_exit_arrow_1")
        self.at_forward_exit_sensor = QtWidgets.QWidget(self.widget)
        self.at_forward_exit_sensor.setGeometry(QtCore.QRect(320, 139, 120, 2))
        self.at_forward_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_forward_exit_sensor.setObjectName("at_forward_exit_sensor")
        self.at_forward_exit_arrow_2 = QtWidgets.QToolButton(self.widget)
        self.at_forward_exit_arrow_2.setGeometry(QtCore.QRect(430, 130, 21, 21))
        self.at_forward_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_forward_exit_arrow_2.setText("")
        self.at_forward_exit_arrow_2.setArrowType(QtCore.Qt.LeftArrow)
        self.at_forward_exit_arrow_2.setObjectName("at_forward_exit_arrow_2")
        self.factory_label = QtWidgets.QLabel(self.widget)
        self.factory_label.setGeometry(QtCore.QRect(580, 10, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.factory_label.setFont(font)
        self.factory_label.setObjectName("factory_label")
        self.factory_indicator = QtWidgets.QLabel(self.widget)
        self.factory_indicator.setGeometry(QtCore.QRect(640, 40, 21, 21))
        self.factory_indicator.setStyleSheet("border:1px solid black; border-radius: 10px; background: rgb(0,255,0);")
        self.factory_indicator.setText("")
        self.factory_indicator.setObjectName("factory_indicator")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(750, 0, 201, 781))
        self.widget_2.setObjectName("widget_2")
        self.date_label = QtWidgets.QLabel(self.widget_2)
        self.date_label.setGeometry(QtCore.QRect(20, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.time_label = QtWidgets.QLabel(self.widget_2)
        self.time_label.setGeometry(QtCore.QRect(20, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.init_button = QtWidgets.QPushButton(self.widget_2)
        self.init_button.setGeometry(QtCore.QRect(20, 630, 161, 31))
        self.init_button.setObjectName("init_button")
        self.start_button = QtWidgets.QPushButton(self.widget_2)
        self.start_button.setGeometry(QtCore.QRect(20, 680, 161, 31))
        self.start_button.setToolTip("")
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.widget_2)
        self.stop_button.setGeometry(QtCore.QRect(20, 730, 161, 31))
        self.stop_button.setObjectName("stop_button")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(0, 0, 3, 780))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.sensors_label = QtWidgets.QLabel(self.widget_2)
        self.sensors_label.setGeometry(QtCore.QRect(20, 160, 161, 361))
        self.sensors_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sensors_label.setText(
            "<html><head/><body><p><span style=\" font-weight:600;\">S1</span>              Sent from left </p><p><span style=\" font-weight:600;\">S2</span>   Sent from right </p><p><span style=\" font-weight:600;\">S3</span>   At scale entry </p><p><span style=\" font-weight:600;\">S4</span>  At scale </p><p><span style=\" font-weight:600;\">S5</span>   At scale exit </p><p><span style=\" font-weight:600;\">S6</span>   At left entry </p><p><span style=\" font-weight:600;\">S7 </span>  At left exit </p><p><span style=\" font-weight:600;\">S8</span>   At forward entry </p><p><span style=\" font-weight:600;\">S9</span>   At forward exit </p><p><span style=\" font-weight:600;\">S10</span> At right entry </p><p><span style=\" font-weight:600;\">S11</span> At right exit </p></body></html>")
        self.sensors_label.setObjectName("sensors_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.init_button.clicked.connect(self.init_script)
        self.start_button.clicked.connect(self.start_script)
        self.start_button.setDisabled(True)
        self.stop_button.clicked.connect(self.stop_script)
        self.stop_button.setDisabled(True)

        self.left_emitter_switch.clicked.connect(self.left_emitter_click)
        self.right_emitter_switch.clicked.connect(self.right_emitter_click)
        self.entry_conveyor_switch.clicked.connect(self.entry_conveyor_click)
        self.load_scale_switch.clicked.connect(self.load_scale_click)

        self.changed = QtCore.QTimer()
        self.changed.timeout.connect(self.updateTime)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.front_remover_label.setText(_translate("MainWindow", "Front\n"
                                                                  "remover"))
        self.left_remover_label.setText(_translate("MainWindow", "Left\n"
                                                                 "remover"))
        self.right_remover_label.setText(_translate("MainWindow", "Right\n"
                                                                  "remover"))
        self.front_conveyor_label.setText(_translate("MainWindow", "Front\n"
                                                                   "conveyor"))
        self.sorter_label.setText(_translate("MainWindow", "Sorter"))
        self.left_conveyor_label.setText(_translate("MainWindow", "Left conveyor"))
        self.right_conveyor_label.setText(_translate("MainWindow", "Right conveyor"))
        self.load_scale_label.setText(_translate("MainWindow", "Load\n"
                                                               "scale"))
        self.entry_conveyor_label.setText(_translate("MainWindow", "Entry\n"
                                                                   "conveyor"))
        self.send_label.setText(_translate("MainWindow", "Sender"))
        self.front_right_conveyor_label.setText(_translate("MainWindow", "Front right\n"
                                                                         "conveyor"))
        self.front_left_conveyor_label.setText(_translate("MainWindow", "Front left\n"
                                                                        "conveyor"))
        self.right_emitter_label.setText(_translate("MainWindow", "Right\n"
                                                                  "emitter"))
        self.left_emitter_label.setText(_translate("MainWindow", "Left\n"
                                                                 "emitter"))
        self.at_scale_entry_label.setText(_translate("MainWindow", "S3"))
        self.at_scale_label.setText(_translate("MainWindow", "S4"))
        self.at_scale_exit_label.setText(_translate("MainWindow", "S5"))
        self.front_counter_label.setText(_translate("MainWindow", "<b>CNT:</b> 0"))
        self.weight_label.setText(_translate("MainWindow", "Weight: 0.00"))
        self.left_counter_label.setText(_translate("MainWindow", "<b>CNT:</b> 0"))
        self.right_counter_label.setText(_translate("MainWindow", "<b>CNT:</b> 0"))
        self.at_forward_entry_label.setText(_translate("MainWindow", "S8"))
        self.at_right_entry_label.setText(_translate("MainWindow", "S10"))
        self.at_left_entry_label.setText(_translate("MainWindow", "S6"))
        self.at_right_exit_label.setText(_translate("MainWindow", "S11"))
        self.at_left_exit_label.setText(_translate("MainWindow", "S7"))
        self.sent_from_right_label.setText(_translate("MainWindow", "S2"))
        self.sent_from_left_label.setText(_translate("MainWindow", "S1"))
        self.at_forward_exit_label.setText(_translate("MainWindow", "S9"))
        self.factory_label.setText(_translate("MainWindow", "Factory I/O running"))
        self.date_label.setText(_translate("MainWindow",
                                           "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Date:</span></p></body></html>"))
        self.time_label.setText(_translate("MainWindow",
                                           "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Time:</span></p></body></html>"))
        self.init_button.setText(_translate("MainWindow", "Init"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))

        # time
        self.datetime = QtCore.QDateTime.currentDateTime()
        self.time_label.setText("<b>Time:</b> " + self.datetime.toString("hh:mm:ss"))
        self.date_label.setText("<b>Date:</b> " + self.datetime.toString("dd-MM-yyyy"))

        self.tractor = ProductionLine()

        self.changed.start(500)

    def left_emitter_click(self):
        bg_color = Qt.green if self.left_emitter_switch.isChecked() else Qt.red
        self.tractor.state_left_emitter = True if self.left_emitter_switch.isChecked() else False

        self.le = threading.Thread(target=self.tractor.turning_on_off_left_emitter(self.tractor.state_left_emitter))
        self.le.start()

        if bg_color == Qt.green:
            self.left_emitter_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        else:
            self.left_emitter_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")

    def right_emitter_click(self):
        bg_color = Qt.green if self.right_emitter_switch.isChecked() else Qt.red
        self.tractor.state_right_emitter = True if self.right_emitter_switch.isChecked() else False

        self.re = threading.Thread(target=self.tractor.turning_on_off_right_emitter(self.tractor.state_right_emitter))
        self.re.start()

        if bg_color == Qt.green:
            self.right_emitter_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        else:
            self.right_emitter_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")

    def entry_conveyor_click(self):
        bg_color = Qt.green if self.entry_conveyor_switch.isChecked() else Qt.red
        self.tractor.state_entry_conveyor = True if self.entry_conveyor_switch.isChecked() else False

        self.z = threading.Thread(target=self.tractor.turning_on_off_entry_conveyor(self.tractor.state_entry_conveyor))
        self.z.start()

        if bg_color == Qt.green:
            self.entry_conveyor_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        else:
            self.entry_conveyor_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")

    def load_scale_click(self):
        bg_color = Qt.green if self.load_scale_switch.isChecked() else Qt.red
        self.tractor.state_load_scale = True if self.load_scale_switch.isChecked() else False

        self.a = threading.Thread(target=self.tractor.turning_on_off_load_scale(self.tractor.state_load_scale))
        self.a.start()

        if bg_color == Qt.green:
            self.load_scale_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
        else:
            self.load_scale_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")

    def updateTime(self):
        datetime = QtCore.QDateTime.currentDateTime()
        self.time_label.setText("<b>Time:</b> " + datetime.toString("hh:mm:ss"))
        if (datetime.toString("hh:mm:ss") == "00:00:00"):
            self.date_label.setText("<b>Date:</b> " + datetime.toString("dd.MM.yyyy"))

        if self.tractor.state_running:
            self.factory_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 10px; background: rgb(0,255,0);")
        else:
            self.factory_indicator.setStyleSheet(
                "border:1px solid black; border-radius: 10px; background: rgb(255,0,0);")

        if self.tractor.state_running:
            if self.tractor.state_entry_conveyor:
                self.entry_conveyor_switch.setChecked(True)
                self.entry_conveyor_indicator.setStyleSheet(
                    "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
            else:
                self.entry_conveyor_switch.setChecked(False)
                self.entry_conveyor_indicator.setStyleSheet(
                    "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")

            if self.tractor.state_load_scale:
                self.load_scale_switch.setChecked(True)
                self.load_scale_indicator.setStyleSheet(
                    "border:1px solid black; border-radius: 7px; background: rgb(0,255,0);")
            else:
                self.load_scale_switch.setChecked(False)
                self.load_scale_indicator.setStyleSheet(
                    "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")

            if self.tractor.state_at_scale:
                self.weight_label.setText("<b>Weight: </b>" + str(round(self.tractor.weight, 2)))
                self.at_scale_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_scale_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_scale_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_scale_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_scale_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_scale_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_sent_from_left:
                self.sent_from_left_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.sent_from_left_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.sent_from_left_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.sent_from_left_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.sent_from_left_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.sent_from_left_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_sent_from_right:
                self.sent_from_right_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.sent_from_right_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.sent_from_right_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.sent_from_right_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.sent_from_right_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.sent_from_right_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_sender_front:
                self.send_front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,255,0);")
            else:
                self.send_front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")

            if self.tractor.state_sender_right:
                self.send_right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,255,0);")
            else:
                self.send_right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")

            if self.tractor.state_sender_left:
                self.send_left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,255,0);")
            else:
                self.send_left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")

            if self.tractor.state_at_scale_entry:
                self.at_scale_entry_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_scale_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_scale_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_scale_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_scale_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_scale_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_at_scale_exit:
                self.weight_label.setText("<b>Weight: </b>" + str(round(self.tractor.weight, 2)))
                self.at_scale_exit_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_scale_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_scale_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_scale_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_scale_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_scale_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_sorter_front:
                self.front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,255,0);")
            else:
                self.front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")

            if self.tractor.state_sorter_right:
                self.right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,255,0);")
            else:
                self.right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")

            if self.tractor.state_sorter_left:
                self.left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,255,0);")
            else:
                self.left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")

            if self.tractor.state_at_left_entry:
                self.left_counter_label.setText("<b>CNT:</b> " + str(self.tractor.counter_left))
                self.at_left_entry_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_left_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_left_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_left_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_left_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_left_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_at_forward_entry:
                self.front_counter_label.setText("<b>CNT:</b> " + str(self.tractor.counter_forward))
                self.at_forward_entry_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_forward_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_forward_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_forward_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_forward_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_forward_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_at_right_entry:
                self.right_counter_label.setText("<b>CNT:</b> " + str(self.tractor.counter_right))
                self.at_right_entry_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_right_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_right_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_right_entry_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_right_entry_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_right_entry_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_at_left_exit:
                self.at_left_exit_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_left_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_left_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_left_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_left_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_left_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_at_forward_exit:
                self.at_forward_exit_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_forward_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_forward_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_forward_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_forward_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_forward_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

            if self.tractor.state_at_right_exit:
                self.at_right_exit_sensor.setStyleSheet("border:2px dotted rgb(0, 128, 0);")
                self.at_right_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
                self.at_right_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(0,128,0);")
            else:
                self.at_right_exit_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
                self.at_right_exit_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
                self.at_right_exit_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")


    def run_init_script(self):
        init_script.start()
        self.tractor.init_variables()

    def init_script(self):
        self.y = threading.Thread(target=self.run_init_script)
        self.y.start()
        self.init_button.setDisabled(True)
        self.start_button.setDisabled(False)
        self.stop_button.setDisabled(True)

        self.tractor.init_variables()

        self.left_emitter_switch.setChecked(False)
        self.right_emitter_switch.setChecked(False)
        self.entry_conveyor_switch.setChecked(False)
        self.load_scale_switch.setChecked(False)
        self.left_counter_label.setText("<b>CNT:</b> " + str(self.tractor.counter_left))
        self.front_counter_label.setText("<b>CNT:</b> " + str(self.tractor.counter_forward))
        self.right_counter_label.setText("<b>CNT:</b> " + str(self.tractor.counter_right))

        self.entry_conveyor_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")
        self.load_scale_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")
        self.left_emitter_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")
        self.right_emitter_indicator.setStyleSheet(
            "border:1px solid black; border-radius: 7px; background: rgb(255,0,0);")
        self.left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")
        self.front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")
        self.right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")
        self.send_left_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")
        self.send_front_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")
        self.send_right_arrow.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(255,0,0);")
        self.factory_indicator.setStyleSheet("border:1px solid black; border-radius: 10px; background: rgb(255,0,0);")

        # at scale sensor
        self.at_scale_sensor.setStyleSheet("border:2px dotted rgb(128, 0, 0);")
        self.at_scale_arrow_1.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")
        self.at_scale_arrow_2.setStyleSheet("border:0px solid rgb(0, 0, 0); color: rgb(128,0,0);")

    def run_script(self):
        if self.left_emitter_switch.isChecked():
            if self.right_emitter_switch.isChecked():
                self.tractor.USE_BOTH_EMITTORS = True
            else:
                self.tractor.USE_LEFT_EMITTOR = True
        else:
            self.tractor.USE_RIGHT_EMITTOR = True

        self.tractor.start()

    def start_script(self):
        self.tractor.stop_running = False

        self.threads = threading.Thread(target=self.tractor.run_threads)
        self.threads.start()

        self.x = threading.Thread(target=self.run_script)
        self.x.start()
        self.start_button.setDisabled(True)
        self.init_button.setDisabled(True)
        self.stop_button.setDisabled(False)

    def stop_script(self):
        self.tractor.stop_running = True
        self.ss = threading.Thread(target=self.tractor.turn_off_factory)
        self.ss.start()

        self.stop_button.setDisabled(True)
        self.init_button.setDisabled(False)
        self.start_button.setDisabled(True)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    app.aboutToQuit.connect(closeEvent)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
    MainWindow.setFixedSize(950, 781)
    MainWindow.setWindowTitle(WIN_TITLE)
    MainWindow.show()
    sys.exit(app.exec_())

